# Generated by Django 5.1.2 on 2024-10-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_contact_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_company',
            old_name='comapany_name',
            new_name='company_name',
        ),
    ]
