# Generated by Django 5.1.2 on 2024-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_rename_comapany_name_contact_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='image',
            field=models.ImageField(upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos'),
        ),
    ]
