# Generated by Django 5.1.2 on 2024-10-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_allproduct_image_alter_allproduct_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
