# Generated by Django 5.1.2 on 2024-10-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotdealscountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HOT DEALS THIS WEEK', max_length=100)),
                ('description', models.TextField(default='NEW COLLECTION UP TO 50% OFF')),
                ('end_date_time', models.DateTimeField()),
            ],
        ),
    ]
