# Generated by Django 5.1.2 on 2024-11-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_hotdealscountdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_company',
            name='about_us',
            field=models.TextField(default='We Electro Jungle have networks and offices throught the world. bla blaaaaaaaaaaaaaa.'),
        ),
    ]
