# Generated by Django 5.1.2 on 2024-11-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_contact_company_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_company',
            name='Terms_and_conditions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contact_company',
            name='privacy_policy',
            field=models.TextField(default=''),
        ),
    ]
