# Generated by Django 5.1.2 on 2024-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_contact_company_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_company',
            name='aboutus_main',
            field=models.CharField(default='Our networks and offices are available throught the whole world.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_company',
            name='about_us',
            field=models.TextField(default=''),
        ),
    ]
