# Generated by Django 5.1.2 on 2024-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_allproduct_details_allproduct_explained_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='allproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready for ship', 'Ready for ship'), ('Order shipped', 'Order shipped'), ('Out of delivery', 'Out of delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Customuser',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
