# Generated by Django 5.1.2 on 2024-11-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_remove_otp_user_allproduct_status_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready for ship', 'Ready for ship'), ('Order shipped', 'Order shipped'), ('Out of delivery', 'Out of delivery'), ('Delivered', 'Delivered')], default='', max_length=50),
        ),
    ]
